Modify `build.gradle` to add `tracing` dependency.

[source,java]
.bookinventory/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/bookinventory/build.gradle[tag=tracing]
}
----

To send tracing spans to Jaeger the minimal configuration requires you add the following dependencies to `build.gradle`:

[source,java]
.bookinventory/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/bookinventory/build.gradle[tag=jaeger]
}
----


Append to `bookinventory` service `application.yml` the following snippet:

[source,yaml]
.bookinventory/src/main/resources/application.yml
----
include::{sourceDir}/bookinventory/src/main/resources/application.yml[tag=jaeger]
----

<1> Trace 100% of requests.

Previous configuration registers a Micronaut app with Consul with minimal configuration. Discover a more complete list of Configuration options at https://docs.micronaut.io/snapshot/api/io/micronaut/discovery/consul/ConsulConfiguration.html[ConsulConfiguration].

Disable consul registration in tests:

[source,yaml]
.bookinventory/src/main/resources/application-test.yml
----
include::{sourceDir}/bookinventory/src/main/resources/application-test.yml[tag=jaeger]
----

Annotate `BookController` method with `@ContinueSpan` and the method parameter with `@SpanTag`:

[source,java]
.bookinventory/src/main/java/example/micronaut/bookinventory/BooksController.java
----
include::{sourceDir}/bookinventory/src/main/java/example/micronaut/bookinventory/BooksController.java[]
----

<1> The `@ContinueSpan` annotation will continue an existing span, wrapping the method call or reactive type.
<2> The `@SpanTag` annotation can be used on method arguments to include the value of each argument within a Span's tags.

