Modify `build.gradle` to add `tracing` dependency.

[source,java]
.bookinventory/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/bookinventory/build.gradle[tag=tracing]
}
----

To send tracing spans to Jaeger the minimal configuration requires you add the following dependencies to `build.gradle`:

[source,java]
.bookinventory/build.gradle
----
dependencies {
    ...
    ..
    .
include::{sourceDir}/bookinventory/build.gradle[tag=jaeger]
}
----


Append to `bookinventory` service `application.yml` the following snippet:

[source,yaml]
.bookinventory/src/main/resources/application.yml
----
include::{sourceDir}/bookinventory/src/main/resources/application.yml[tag=jaeger]
----

<1> Trace 100% of requests.

In production, you will probably want to small percentage of the requests. In order to keep guide easy, we set it to trace 100%.

Disable distributed tracing in tests:

[source,yaml]
.bookinventory/src/main/resources/application-test.yml
----
include::{sourceDir}/bookinventory/src/main/resources/application-test.yml[tag=jaeger]
----

Annotate the method parameter with `@SpanTag`:

[source,java]
.bookinventory/src/main/java/example/micronaut/bookinventory/BooksController.java
----
include::{sourceDir}/bookinventory/src/main/java/example/micronaut/bookinventory/BooksController.java[]
----

<2> The `@SpanTag` annotation can be used on method arguments to include the value of each argument within a Span's tags.

